# Adapted from: https://github.com/crate-ci/cargo-release/blob/v0.25.15/.github/workflows/post-release.yml
name: "Release"

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

env:
  BIN_NAME: pung

jobs:
  build-release:
    name: build-release
    strategy:
      fail-fast: false
      matrix:
        build: [linux, macos-arm64]
        include:
        - build: linux
          os: ubuntu-latest
          rust: stable
          target: x86_64-unknown-linux-gnu
        - build: macos-arm64
          os: macos-latest
          rust: stable
          target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}

    - name: Install cargo-edit to set version
      run: cargo install cargo-edit

    - name: Set version
      run: cargo set-version "${{ github.ref_name }}"

    - name: Build release binary
      run: cargo build --target ${{ matrix.target }} --verbose --release --bin ${{ env.BIN_NAME }}
    - name: Build archive
      shell: bash
      run: |
        outdir="./target/${{ matrix.target }}/release"
        staging="${{ env.BIN_NAME }}-${{ github.ref_name }}-${{ matrix.target }}"
        mkdir -p "$staging"
        cp README.md "$staging/"
        if [ -f LICENSE ]; then
          cp LICENSE "$staging/"
        fi
        cp "target/${{ matrix.target }}/release/${{ env.BIN_NAME }}" "$staging/"
        tar czf "$staging.tar.gz" -C "$staging" .
        echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.ASSET }}
        token: ${{ secrets.RELEASE_TOKEN }}
